QMAKE_TARGET_DESCRIPTION = ZENO-Setup
QMAKE_TARGET_PRODUCT = zenustech
QMAKE_TARGET_COMPANY = zenustech.com
QMAKE_TARGET_COPYRIGHT = Copyright(C)2021 zenustech.com
VERSION = 1.0.0.1
RC_ICONS = $$PWD/icon.ico
RC_CODEPAGE = 936
RC_LANG = 0x804
